### PR TITLE
Fix to jQuery library inclusion in bootstrap.vm, Mexican Spanish translation and fixes to Spanish translation 

### PR DESCRIPTION
**Pull request by rafafallo**
Hello,

I have had problems for BBB to work in Sakai 11, and so I discovered they were due to a problem in the inclusion of the jQuery library (assumed in Sakai's library, but available in BBB's).

I have created a Mexican Spanish translation of BBB, based on the Spanish translation, so I discovered some small problems in the original translation and I fixed them.

### CODE REVIEW

**Comment by jfederico** [comment]
The content in the bbb-tool directory was moved to the root. Can you make the adjustments to your repo so the merge can be done?

**Comment by jfederico** [comment]
Also, the jquery file should be taken from:

/library/webjars/jquery/1.11.3/jquery.min.js

**Comment by rafafallo** [comment]
It's true. I did not see that one before. However, if there is one in 
the bigbluebutton-sakai package, wouldn't it be better to use that one?

**Comment by jfederico** [comment]
No it is not. The old version must be there because it was used in previous versions. It is always better to avoid duplication. In fact all those versions will be removed.

**Comment by rafafallo** [comment]
OK Done! Do I need to do anything else?

**Pull request merged**
